server:
  port: 9081
  servlet:
    context-path: /
spring:
  application:
    name: pay-service-provider

dubbo:
  application:
    metadata-type: local
  protocol:
    name : dubbo
    port: 25002
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.springboot.dubbo.web
  consumer:
    check: false
    timeout: 15000
    retries: 0
    cluster: failover
  provider:
    timeout: 10000
    retries: 0
    cluster: failover
logging:
  level:
    root: info
